language : node_js
node_js:
  - node_js
services:
  -postgresql
before_script:
  -npm install -g codeclimate-test-reporter
  -npm run test.js
script:
  -npm test
after_success:
-CODECLIMATE_REPO_TOKEN=CODECLIMATE_TOKEN codeclimate-test-reporter < coverage/lcov.info