language: node_js

node_js:
  - node
  - 6.11.3 

services:
  - postgresql

script:
  - npm run test

env:
  - NODE_ENV=test

before_script: 
  - psql -c 'drop database if exists travis;' -U postgres
  - psql -c 'create database travis;' -U postgres

after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN coverage/lcov.info
  - npm run coveralls