export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_BOOKS = 'GET_BOOKS';

export const BORROW_BOOKS = 'BORROW_BOOKS';

export const ADD_BOOKS = 'ADD_BOOKS';

export const DELETE_BOOKS = 'DELETE_BOOKS';

export const MODIFY_BOOKS = 'MODIFY_BOOKS';

export const PUT_BOOKS = 'PUT_BOOKS';

export const GET_USER = 'GET_USER';

export const SET_PROFILE = 'SET_PROFILE';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

export const GET_PROFILE = 'GET_PROFILE';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const GET_BOOKS_COUNT = 'GET_BOOKS_COUNT';

export const GET_RENTED_BOOKS_COUNT = 'GET_RENTED_BOOKS_COUNT';

export const COUNT_USERS = 'COUNT_USERS';

export const SAVE_IMAGE_SUCCESSFUL = 'SAVE_IMAGE_SUCCESSFUL';

export const SAVE_IMAGE_FAILED = 'SAVE_IMAGE_FAILED';

export const SAVE_IMAGE_REQUEST = 'SAVE_IMAGE_REQUEST';

export const CREATE_BOOKS_SUCCESSFUL = 'CREATE_BOOKS_SUCCESSFUL';

export const CREATE_BOOKS_FAILED = 'CREATE_BOOKS_FAILED';

export const CREATE_BOOKS_REQUEST = 'CREATE_BOOKS_REQUEST';
