module.exports = {
  'Admin Actions': (browser) => {
    browser
      .url('http://localhost:8000/login')
      .waitForElementVisible('form', 1000)
      .pause(2000)
      .setValue('input[id=email]', 'admin96@gmail.com')
      .setValue('input[id=password]', '1996')
      .waitForElementVisible('button[name=action]', 1000)
      .click('button[name=action]')
      .pause(2000)
      .assert.containsText('h4', 'PROFILE DETAILS')
      .assert.containsText('p', 'Admin Tosin')
      .click('button[name=action]')
      .pause(2000)
      .setValue('input[id=verifyPassword]', '1996')
      .setValue('input[id=password]', '1996')
      .waitForElementVisible('button[id=passwordButton]', 1000)
      .waitForElementVisible('button[id=passwordCButton]', 1000)
      .click('button[id=passwordButton]')
      .click('button[id=passwordCButton]')
      .pause(2000)
      .waitForElementVisible('div.profile', 1000)
      .waitForElementVisible('li[name=dashboard]', 1000)
      .click('li[name=dashboard]')
      .pause(2000)
      .waitForElementVisible('a.modal-trigger', 1000)
      .click('a.modal-trigger')
      .pause(2000)
      .setValue('input[id=category]', 'Play Time')
      .waitForElementVisible('button[type=submit]', 1000)
      .waitForElementVisible('button[id=cancelButton]', 1000)
      .click('button[type=submit]')
      .click('button[id=cancelButton]')
      .pause(2000)
      .click('li[name=addbooks]')
      .pause(2000)
      .assert.containsText('h4', 'ADMIN UPLOAD BOOKS')
      .click('li[name=books]')
      .pause(2000)
      .assert.containsText('h4', 'ADMIN BOOK LIST')
      .assert.containsText('th', 'Image')
      .click('button[id=editBook]')
      .pause(2000)
      .waitForElementVisible('form', 1000)
      .setValue('select[id=category]', 'Fiction')
      .setValue('input[id=title]', 'Abuja')
      .setValue('textarea[id=review]', 'Nice Nice Book')
      .click('li[name=books]')
      .pause(2000)
      .assert.containsText('h4', 'ADMIN BOOK LIST')
      .waitForElementVisible('button[id=deleteBook]', 1000)
      .assert.containsText('h4', 'ADMIN BOOK LIST')
      .waitForElementVisible('li[name=logout]', 1000)
      .click('li[name=logout]')
      .pause(2000)
      .assert.containsText('h1', 'Welcome to Hello Books')
      .end();
  },
};

