module.exports = {
  'User Actions': (browser) => {
    browser
      .url('http://localhost:8000/login')
      .waitForElementVisible('form', 1000)
      .pause(2000)
      .setValue('input[id=email]', 'cora@gmail.com')
      .setValue('input[id=password]', 'coraldraw')
      .waitForElementVisible('button[name=action]', 1000)
      .click('button[name=action]')
      .pause(2000)
      .assert.containsText('h4', 'PROFILE DETAILS')
      .assert.containsText('p', 'chidinma orajiaku')
      .click('button[name=action]')
      .pause(2000)
      .setValue('input[id=verifyPassword]', 'coraldraw')
      .setValue('input[id=password]', 'coraldraw')
      .waitForElementVisible('button[id=passwordButton]', 1000)
      .waitForElementVisible('button[id=passwordCButton]', 1000)
      .click('button[id=passwordButton]')
      .click('button[id=passwordCButton]')
      .pause(2000)
      .waitForElementVisible('div.profile', 1000)
      .waitForElementVisible('li[name=library]', 1000)
      .click('li[name=library]')
      .pause(2000)
      .assert.containsText('h4', 'USER LIBRARY')
      .waitForElementVisible('span.card-title.activator > i', 1000)
      .click('span.card-title.activator > i')
      .pause(2000)
      .assert.containsText('span.card-title.grey-text', 'Book Details')
      .waitForElementVisible('button[id=libraryAction]', 1000)
      .click('button[id=libraryAction]')
      .pause(2000)
      .waitForElementVisible('li[name=history]', 1000)
      .click('li[name=history]')
      .pause(2000)
      .assert.containsText('h4', 'USER BOOK HISTORY')
      .assert.containsText('th', 'Image')
      // .click('select[id=bookStatus]', 'Pending Returns')
      // .pause(2000)
      // .assert.containsText('th', 'Return')
      // .waitForElementVisible('button[id=returnAction]', 1000)
      // .click('button[id=returnAction]')
      .waitForElementVisible('li[name=logout]', 1000)
      .click('li[name=logout]')
      .pause(2000)
      .assert.containsText('h1', 'Welcome to Hello Books')
      .end();
  },
};
